[package]
name = "typua-ty"
version = "0.1.0"
edition = "2024"

[lib]
name = "typua_ty"
path = "src/lib.rs"

[dependencies]
typua-span.workspace = true
thiserror.workspace = true
full_moon.workspace = true
tower-lsp.workspace = true
