[runtime]
version = "luajit" # default luajit, other version lua51, lua52, lua53, lua54
path = [
    "?.lua",
    "?/init.lua"
]
path_strict = false

[workspace]
library = [
    "lua",
    "$VIMRUNTIME",
]
ignore_dir = [
    "target"
]
