[package]
name = "typua-checker"
version = "0.1.0"
edition = "2024"

[dependencies]
typua-parser.workspace = true
typua-binder.workspace = true
typua-ty.workspace = true
typua-span.workspace = true

pretty_assertions.workspace = true
