[package]
name = "typua-binder"
version = "0.1.0"
edition = "2024"

[lib]
name = "typua_binder"
path = "src/lib.rs"

[dependencies]
typua-parser.workspace = true
typua-ty.workspace = true
im.workspace = true
itertools.workspace = true
